# Building A Layer Lab

### Introduction

In the last lesson, we saw what it meant to build a layer of a neural network.  Each **individual neuron** in a layer can be represented by a *vector* of weights and a bias, and an entire *layer* can be represented by a **matrix of weights** and a bias vector.  In this lesson, we'll work towards making predictions with the layer of a network.

### Back to a single neuron

Let's say a dataset where each observation is a different cell.  And we want to train a network to determine if cell is cancerous.

Each observation has the following features of:

* perimeter, area, radius, asymmetry, and indentations, and in that order

We represent our first observation's features with the $x$ vector below.

In [2]:
import numpy as np
x = np.array([2, 1, 1, 5, 4])
# perimeter, radius, volume, asymmetries, bumpiness    

In [3]:
x

array([2, 1, 1, 5, 4])

So the vector $x$ represents an observation that has a perimeter of 2, radius of 1, volume of 1, 5 for asymmetries and 4 for bumpiness.

### Constructing a neuron

Now let's say that we have a neuron that judges if a cell is large or small.  The neuron has weights of 2, 1, and 3 for `perimeter`, `radius` and `volume`.  It does not factor in assymetries or smoothness so it the corresponding weights for these two features are 0.  Write a vector to represent the weights of this neuron.

> Make sure you use a numpy array to represent the vector.

In [20]:
import numpy as np
w_size = None

Let's assume that the bias of the neuron is -5.

In [8]:
b_size = -5

Use the dot product, along with addition to calculate the output of the neuron linear's component when it's provided the $x$ observation above.  

In [21]:
# use the dot product and addition 

# 3

Now use the sigmoid function to turn this into a prediction between 0 and 1.  Remember that the formula for the sigmoid function is: $\sigma = \frac{1}{1 + e ^{-x}}$

In [8]:
def sigmoid(value):
    None

In [9]:
sigmoid(size_linear_comp)
# 0.9525741268224334

Here is an array representing the weights of a second neuron.

In [22]:
w_noncircular = np.array([0, 0, 0, 2, 1])
# perimeter, radius, volume, # asymmetries, bumpiness    

The `noncircular` neuron determines if a cell is noncircular, with a 1 indicating non-circular.  Let's assume the neuron has a bias of **negative 10**.  Use the neuron's linear component, along with the sigmoid function to compute the output from the `noncircular` neuron.  The prediction should be between 0 and 1.

In [10]:
# prediction = None
# prediction
# .982

0.9820137900379085

### Building a layer

Ok, now let's make a predictions from the size and circular neurons at the same time. 

1. Construct a weight matrix called `W` where the first column represents the weights of the size neuron and the second column represents the weights of the noncircular neuron.

> **Hint**: We can *stack* two vectors vertically -- $v_1$ and $v_2$ -- together in a matrix with `np.stack([v_1, v_2]).T`.

In [15]:
# fill in the correct vectors below
W = np.stack().T
W

# array([[2, 0],
#        [1, 0],
#        [3, 0],
#        [0, 2],
#        [0, 1]])

array([[2, 0],
       [1, 0],
       [3, 0],
       [0, 2],
       [0, 1]])

2. Construct a vector of representing the biases of each neuron (-5 for the size neuron and -10 for noncircular neuron).

In [23]:
b = None

Now use the dot product and vector addition to calculate the output of the linear layer.

In [24]:
# write code here

# array([3, 4])

Finally, use the weight matrix along with the `sigmoid` function to calculate the outputs of our two sigmoid neurons given our input vector `x`.

In [19]:
#  predictions

# array([0.95257413, 0.98201379])

array([0.95257413, 0.98201379])