# Building Layers

### Introduction

In the last lesson, we learned about initializing a layer to our neural network.  We did so by building a weight matrix where we specified the dimensions of the attributes of the layer - a column for each neuron, and a row for each feature that the neuron accepts.  For example, we constructed a linear layer with two neurons, each of which accepts five features as the following:

In [22]:
import numpy as np
W = np.random.randn(5, 2)
W

array([[-2.34360319,  1.16152149],
       [ 0.38607805, -1.13313327],
       [ 0.43309255, -0.30408644],
       [ 2.58529487,  1.83533272],
       [ 0.44068987, -0.71925384]])

In [23]:
b = np.random.randn(2)
b

array([-0.58341459, -0.32504963])

In this lesson we'll move beyond constructing single layers and learn how to build a network with multiple layers.

### Multiple Layers

Let's start by taking another look at our single layer matrix:

<img src="https://storage.googleapis.com/curriculum-assets/nn-from-scratch/first-layer.png" width="20%">

Now let's imagine that each observation in our training data has 10 features.  For example let's say, our feature vector $x$, representing our first observation looks like the following: 

In [3]:
x = np.array([.9, .4, .5])

To build a layer that takes in a feature vector of this size, we need a matrix where each row has 3 rows.  And let's have a layer with five neurons, giving us five columns.

In [25]:
import numpy as np
np.random.seed(2)
W_1 = np.random.randn(3, 5)

Our bias vector has five entries, one for each neuron.

In [26]:
b_1 = np.random.randn(5)
b_1

array([-0.5961597 , -0.0191305 ,  1.17500122, -0.74787095,  0.00902525])

Now let's pass our first observation through the linear layer, and then the sigmoid function for the activation layer.

In [29]:
def sigmoid(value): return 1/(1 + np.exp(-value))

l1 = x.dot(W_1) + b_1
a1 = sigmoid(l1)
a1

array([0.26265516, 0.78202152, 0.22707164, 0.43689559, 0.15457753])

So we can see that we get five different outputs ranging from 0 to 1, one for each of our neurons. 

Now if we want to add a second layer to our neural network, we take the five outputs from the neurons in our first layer and feed these ouputs to each neurons in our second layer.

> This is called a **fully connected** neural network.  In a fully connected neural network, every neuron in one layer connects to every neuron in another layer.

In this case, the number of features accepted by a neuron in one layer must equal the number of inputs it receives from the previous layer.  

In contrast to the features, the number of *neurons* that composes each layer is not constrained by previous layers.  

* Or to put this in terms of our weight matrix, the number of columns in a weight matrix is equal to the number of the neurons in the previous layer, as each neuron outputs a single number. 

### Walking through an example

Let's see this with our example above.  We start with an observation's feature vector that has three entries.

In [30]:
x

array([0.9, 0.4, 0.5])

This means our weight matrix must have three columns (one for each corresponding feature of the neuron).  And we previously specified that there be three columns, to represent the weights of three neurons.

In [31]:
W_1

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801,  0.04153939, -1.11792545,  0.53905832]])

And the outputs of the neurons' linear components are.

In [34]:
x.dot(W_1) + b_1

array([-1.03221369,  1.27748593, -1.2249208 , -0.25377083, -1.69914066])

In [35]:
sigmoid(x.dot(W_1) + b_1)

array([0.26265516, 0.78202152, 0.22707164, 0.43689559, 0.15457753])

Because we get an output from each of the five neurons, our next weight matrix, $l2$ must have five rows, one row for the weights of each neuron.

> We'll initialize it to have two neurons.  Each column in the weight matrix represents a neuron.

In [36]:
W_2 = np.random.randn(5, 2)
W_2

array([[-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229],
       [-1.42121723, -0.1534952 ]])

> And there is a bias term for each neuron.

In [37]:
b_2 = np.random.randn(2)
b_2

array([-0.26905696,  2.23136679])

### Wrapping Up

We can initialize our weights and biases so that our layers are fully connected.

In [38]:
x = np.array([0.9, 0.4, 0.5])
W_1 = np.random.randn(3, 5)
b_1 = np.random.randn(5)
# outputs a prediction from each of five neurons

W_2 = np.random.randn(5, 2)
b_2 = np.random.randn(2)
# outputs a prediction from each of two neurons

W_1.shape, W_2.shape

((3, 5), (5, 2))

And then we feed forward our neural network.

In [39]:
l1 = sigmoid(x.dot(W_1) + b_1)
l2 = sigmoid(l1.dot(W_2) + b_2)
l2

array([0.39744071, 0.42585218])

> So we can see that we make a different prediction for each layer in the last network.

Notice that we call the network *feedforward* because information flows through the function being evaluated from $x$, through the intermediate computations, and finally to the output of a prediction from each neuron in our last network.

### Summarize

So that is how our neural network makes a prediction.  

1. Initialize random weights and biases for each layer where the number of weights of each neuron are the rows, and there is a separate vector for each neuron.

2. Feed forward each layer with the formula $\sigma(x \cdot W + b)$, where $x$ is the vector of inputs for the first layer, and afterwards $x$ is the vector of the previous layer's outputs

3. For each weight matrix W, the columns represent the number of weights of each neuron and must equal the number of neurons in the previous layer (or for the first layer, the number of features).

<center>
<a href="https://www.jigsawlabs.io/free" style="position: center"><img src="https://storage.cloud.google.com/curriculum-assets/curriculum-assets.nosync/mom-files/jigsaw-labs.png" width="15%" style="text-align: center"></a>
</center>