# Building A Layer Lab

### Introduction

In the last lesson, we saw what it meant to build a layer of a neural network.  Each individual neuron in a layer can be represented by a vector of weights and a bias, and an entire layer can be represented by a matrix of weights and a vector.  Let's begin with building layers of a network in this lab.

### Back to a single neuron

In [2]:
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()


In [3]:
dataset['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

Let's say that we have as our input values X, observations of different cells and we want to train a network to determine if cell is cancerous.

Each observation has the following features of:

* perimeter, area, radius, asymmetry, and indentations

In [4]:
import numpy as np
x = np.array([2, 1, 1, 5, 4])
# 3 perimeter, radius, volume, # asymmetries, bumpiness    

Now let's say that we have one neuron that judges if the size of each cell increases it's likelihood of being cancerous.  The neuron has weights of 2, 1, and 3 for perimeter, radius and volume.  It does not factor in assymetries or smoothness in it's determination of size.  Write a vector to represent the weights of this neuron.

In [5]:
w_size = np.array([2, 1, 3, 0, 0])

Let's assume that the bias of the neuron is -5.  Use matrix algebra to calculate the linear component of the neuron (including the bias).

In [23]:
b_size = -5
size_linear_comp = w_size.dot(x) + b_size
size_linear_comp
# 3

3

Now use the sigmoid function to turn this into a prediction between 0 and 1.  Remember that the formula for the sigmoid function is: $\sigma = \frac{1}{1 + e ^{-x}}$

In [7]:
def sigmoid(value):
    return 1/(1 + np.exp(-value))

In [8]:
sigmoid(size_linear_comp)

0.9525741268224334

Here is an array representing the weights of a second neuron.

In [9]:
w_noncircular = np.array([0, 0, 0, 2, 1])
# 3 perimeter, radius, volume, # asymmetries, bumpiness    

This neuron determines whether or not a cell is non-circular.  Let's assume the neuron has a bias of **negative 10**.  Use this information along with the sigmoid function to predict whether a cell is non-circular.

In [10]:
sigmoid(x.dot(w_noncircular) - 10)
# .982

0.9820137900379085

### Building a layer

Ok, now let's make a prediction of size and non-circular at the same time. 

1. Construct a weight matrix called `W` where the first row represents the weights of the size neuron and the second row represents the weights of the noncircularness neuron.

> **Hint**: We can *stack* two vectors -- $v_1$ and $v_2$ -- together in a matrix with `np.stack([v_1, v_2])`.

In [18]:
W = np.stack([w_size, w_noncircular]).T
W

# array([[2, 1, 3, 0, 0],
#        [0, 0, 0, 2, 1]])

array([[2, 0],
       [1, 0],
       [3, 0],
       [0, 2],
       [0, 1]])

2. Construct a vector of representing the biases of each neuron (-5 for the size neuron and -10 for noncircular neuron).

In [19]:
b = np.array([-5, -10])

Now calculate the outputs of $w\_size\cdot x$ and $w\_noncircular \cdot x$ in one operation, using the weight matrix `W`.

In [21]:
x.dot(w_size)

8

In [22]:
x.dot(w_noncircular)

14

In [ ]:
Now use the weight matrix to calculate the output of the linear layer

In [26]:
x.dot(W) + b

# array([3, 4])

array([3, 4])

Finally, use the weight matrix to calculate the outputs of our two sigmoid neurons given our input vector `x`.

In [27]:
sigmoid(x.dot(W) + b)

# array([0.95257413, 0.98201379])

array([0.95257413, 0.98201379])