# Pytorch Prediction Function

### Reviewing our Hypothesis Function

So far, we have learned how to the components of the prediction function of a single neuron in a neural network.  We saw that we represented our neuron as taking in inputs, and based on those inputs, the corresponding weights, and a bias terms -- firing or not firing. 

<img src="neuron-general-2.png" width="40%">

We saw that our neuron really consists of two components, the linear layer which can return any positive or negative or number, and our activation function which translates that output to a number between 1 and 0 (to represent firing or not).

Mathematically, we represent our neuron's linear function and activation function as the following:

$z(x) = w_1x_1 + w_2x_2 + b$

$ \sigma(z) = \frac{1}{1 + e^{-z}} $

And let's take a moment to review seeing this in code.  

Remember that we can represent an observation as a vector like so.

In [39]:
import torch
# cell area is 3, and cell concavities is 4
x = torch.tensor([2., 4.])

And the linear layer of our neuron can be represented as a weight vector and bias.

In [19]:
# weight cell_area 2, weight for cell_concavities 1
w = torch.tensor([2, 1])
b = torch.tensor(-10)

So to get the outfrom the linear layer, we use the dot product, plus the bias: $z(x) = w \cdot x + b $.

In [22]:
z = w.dot(x) + b
z

tensor(-2)

And then to translate this into a value between $1$ and $0$, we use our sigmoid activation function, $ \sigma(z) = \frac{1}{1 + e^{-z}} $, with the following:

In [27]:
def sigmoid_activation(z):
    return 1/(1 + torch.exp(-z.float()))

> We need to convert our integers into floats, and do so with `z.float()`.

In [28]:
sigmoid_activation(z)

tensor(0.1192)

### Making it Real

Ok, so above we reviewed our prediction function for our neuron.  Now below, let's we'll re-implement that same prediction function function -- the linear layer and the sigmoid layer, but this time we'll use all of the tools that a Pytorch professional would use.  To build a neural network in Pytorch with a single neuron, we generally would do so with the following.

In [35]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

And to have the neural network make a prediction, we just pass through a feature vector like we did above.

In [41]:
# cell area is 3, and cell concavities is 4
x = torch.tensor([2., 4.])

So $x$ represents the features of a single observation.  And we can see our neural network's predictions with the following:

In [42]:
net(x)

tensor([0.9407], grad_fn=<SigmoidBackward>)

> So our linear layer ouputs a positive or negative number, which our sigmoid activation translates to a number between 1 and 0.

So, we'll break down the code above in a moment, but notice it largely consists of what we saw above: `nn.Linear` represents our linear layer and `nn.Sigmoid` represents our sigmoid activation function, and the `nn.Sequential` simply creates a neural network that passes the output from the linear layer to the sigmoid function, just like we saw above.  

$z(x) = w \cdot x + b$

$ \sigma(z) = \frac{1}{1 + e^{-z}} $

### Understanding the Components

Ok, so we just saw how we can create a neural network in Pytorch.

In [43]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

Now let's understand these components a bit better.

The first, and main, component to understand is our `Linear` function -- for linear layer.  This remember, should represent the linear layer of a single neuron.  Notice that we pass through a (2, 1) to `Linear`.  This means that we want the linear function to take in two features -- and the `1` means also that we want it to consist of a single neuron.

In [44]:
ll = nn.Linear(2, 1)

We can see what this looks like under the hood by calling the `_parameters` function.

In [46]:
ll._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[-0.5048, -0.6080]], requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([-0.3516], requires_grad=True))])

So just like the linear function we defined above, here we have a tensor, our weight vector, and a bias term.  Why is the weight vector of length 2?  Because when we created our linear layer, we said there would be 2 input features -- and we need a weight for each feature.

$z(x) = w_1x_1 + w_2x_2 + b$

So we understand the first number in `nn.Linear(2, 1)`, it creates a vector of length 2 for two features.  But what does it mean to create more than one neuron?  Well as we'll see later on, each neuron gets it's own feature vector and it's own bias.  So let's create 3 neurons of length 2.

In [49]:
ll_3 = nn.Linear(2, 3)

In [50]:
ll_3._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[ 0.4237,  0.4814],
                      [ 0.5267, -0.1435],
                      [ 0.0232,  0.5558]], requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([-0.3506, -0.5314, -0.2793], requires_grad=True))])

Now we'll talk about working with multiple neurons later on.  For now let's just make sure we understand our layer with a single neuron.

In [52]:
ll = nn.Linear(2, 1)
ll._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[-0.0883, -0.0319]], requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([0.4128], requires_grad=True))])

It simply creates our weight vector and bias.  And if we pass through a feature vector, it will apply our linear function of $z(x) = w \cdot x + b$ 

In [55]:
x

tensor([2., 4.])

In [54]:
ll(x)

tensor([0.1087], grad_fn=<AddBackward0>)

There we go.

Finally, the sigmoid function takes the output from our linear function and passes it through our sigmoid function.

In [56]:
sigmoid = nn.Sigmoid()

In [60]:
z = ll(x)
sigmoid(z)

tensor([0.5272], grad_fn=<SigmoidBackward>)

And then our `nn.Sequential` function packages up our two functions, and passes the output from one layer into the next layer.

In [61]:
import torch.nn as nn

net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)

### Summary

In this lesson, we saw how to create a neural network -- with a single neuron -- in Pytorch.

In [64]:
net = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

We saw that with the linear layer, we specify the number of input features, and the number of neurons -- where each neuron consists of a weight vector and a bias term.

In [65]:
layer = nn.Linear(2, 1)
layer._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[-0.2977,  0.1892]], requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([-0.3397], requires_grad=True))])

And we saw that we can pass a feature vector to this layer, and it will apply the linear function $z(x) = w \cdot x + b$.

In [66]:
x

tensor([2., 4.])

In [67]:
ll(x)

tensor([0.1087], grad_fn=<AddBackward0>)

And finally that if we pass the feature vector to the neural net, that it will pass the feature vector through the linear layer, and that output to the sigmoid activation function to produce a prediction between 0 and 1 expressing the strength of the neuron firing.

In [68]:
net(x)

tensor([0.2172], grad_fn=<SigmoidBackward>)