# Completing our Predictions

### Introduction

### Refactoring

If we think about our neurons, there are two components.  One is the weight matrix representing the weights of the layers, along with the biases.  This is essentially the current *state* of the layer.  

The second component is what we can do with this layer, which is to make a prediction.  This is what happens when we get an output between 0 and 1 for each of the neurons in the matrix.  

Let's begin to automate these two procedures.

1. Building a random neuron

Now so far we have coded our neurons with being given the weights which the neuron uses to determine the strength of the output.  But as we'll see, the neurons do not know what weights to begin with - rather it learns these weights over time.  

So what this means for us?  It means that we can just start with random weights, and the important thing is to get the dimensions of our neurons, and our layer correct.  Let's walk through this.

Let's say that we have the following observation from our cancerous cells example:

In [1]:
import numpy as np
x = np.array([2, 1, 1, 5, 4])
# 3 perimeter, radius, volume, # asymmetries, bumpiness    

Now to represent the initial weights for a neuron that can accept these features, we simply need to construct a neuron with five random weights - one for each feature.  And with a random bias term.  So here's how we do this in Python.

In [15]:
import numpy as np 
np.random.seed(1)
n_1_w = np.random.randn(1,5)
n_1_w

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763]])

In [22]:
np.random.seed(1)
n_1_b = np.random.randn(1)
n_1_b

array([1.62434536])

So if we want this neuron to make a prediction, it can do so with the following:

In [27]:
def sigmoid(value): return 1/(1 + np.exp(-value))

In [28]:
sigmoid(x.dot(n_1[0]) + n_1_b[0])

0.8617492573700826

Now we don't know if this prediction is any good, or even what this neuron is responsible for predicting.  But that's ok.  We'll worry about that later.  The important thing is that we have one neuron that predicts something.

2. Building a layer

So we built a single neuron with two lines of code - one line to represent the weights.

In [29]:
np.random.randn(1,5)

array([[-0.61175641, -0.52817175, -1.07296862,  0.86540763, -2.3015387 ]])

And another line of code to represent the bias.

In [30]:
np.random.randn(1)

array([1.74481176])

Now in that first line of code, `np.random.randn(1,5)` we are specifying the dimensions of our matrix.  Here we are saying one row and five columns.  The one row represents our single neuron and the five columns are the five weights for our five feature input.

Now if we want to initialize a weight matrix that has two neurons, each with five weights, doing so is not so complicated:

In [32]:
W = np.random.randn(2,5)
W

array([[-0.87785842,  0.04221375,  0.58281521, -1.10061918,  1.14472371],
       [ 0.90159072,  0.50249434,  0.90085595, -0.68372786, -0.12289023]])

And the bias is simply a vector with two entries.

In [34]:
b = np.random.randn(2)
b

array([ 0.53035547, -0.69166075])

And we can make predictions with these neurons with our normal function:

In [36]:
sigmoid(W.dot(x) + b)

array([0.17879491, 0.19855834])

So if we want to build the weights and biases for a neural network that looks like the following:

<img src="./first-layer.png" width="30%">

That's simply four columns (one for each neuron) and four rows (each neuron has four weights) matrix.

In [3]:
import numpy as np
W = np.random.randn(4,4)
W

array([[-0.01791712,  0.20491942,  0.12166726,  0.85470516],
       [-0.54014973,  0.20377669, -0.64654733,  1.51752847],
       [-1.27656353, -0.42488659,  0.02028611, -0.53855715],
       [-0.00312273,  1.6536728 , -1.13278799, -0.18014837]])

In [4]:
b = np.random.randn(4)
b

array([ 0.51094515, -0.4406927 ,  0.58420857,  0.43645582])

So notice that above we have five different neurons, each taking in the the four features of an observation x, and making a prediction.